### ISSUE TITLE
Hyperlinks are not clickable in exported PDF

### ISSUE THREAD

**Issue by An00bRektn** [tcmmichaelb139/obsidian-tokyonight#1]
Not entirely sure if this is an issue with the theme or Obsidian in general.

**Theme Version**: 0.1.8
**Obsidian Version:** 1.2.8
**Problem**: Creating hyperlinks in a markdown document using this theme are not clickable when using the `Export to PDF` option.
**Steps to Reproduce**: Use the `Export to PDF` option on a markdown document (example below) that contains a hyperlink, and open in an app such as Adobe Acrobat or Firefox.

```markdown
# Test Document
This is my [blog](https://notateamserver.xyz)!
```

**Comment by tcmmichaelb139** [comment]
Fixed
