### ISSUE TITLE
Any plan to add various versions of Tokyonight?

### ISSUE THREAD

**Issue by quarkquartet** [tcmmichaelb139/obsidian-tokyonight#10]
Thank you for your work.
e.g. Now at least 3 versions are popular:
Tokyonight, tokyonight light, tokyonight storm.

One more is tokyonight moon, which is popular in the nvim version.

Now we have the first 2. Shall we think about adding more? The storm and moon versions are really cool.

**Comment by tcmmichaelb139** [comment]
Great idea! 

I added the storm and moon style settings configurations with the most recent few commits. Let me know if you notice anything out of place.

**Comment by quarkquartet** [comment]
That works! I downloaded the updated .json files and imported them. Works perfectly!

**Comment by wedgen** [comment]
How do you "import" them?

**Comment by quarkquartet** [comment]
Settings -> Style Settings -> Import (upper right corner)
