### ISSUE TITLE
Style Settings

### ISSUE THREAD

**Issue by not-alaris** [tcmmichaelb139/obsidian-tokyonight#2]
Not an issue, but I was wondering if you would ever implement the style settings plugin to change things such as quote style, heading colors, etc..

I really like your theme, however there are some colors and styles I would like to change for myself personally.

**Comment by Shqrp** [comment]
+1!

**Comment by tcmmichaelb139** [comment]
I have added basic support for the style settings plugin. Further support will be added later.
