### ISSUE TITLE
Is there a way to change the accent color?

### ISSUE THREAD

**Issue by kenjibailly** [tcmmichaelb139/obsidian-tokyonight#3]
Changing the accent color doesn't change the standard cyan.

![image](https://github.com/tcmmichaelb139/obsidian-tokyonight/assets/9883910/222fa8e7-7d6e-44c8-88a6-1a64a19435f6)

**Comment by tcmmichaelb139** [comment]
This should be fixed now. However to have more flexibility, I recommend installing Style Settings.

**Comment by tcmmichaelb139** [comment]
This should be fixed now. However to have more flexibility, I recommend installing Style Settings.

**Comment by kenjibailly** [comment]
Thank you! Very fast support!
