### ISSUE TITLE
External link indicator missing in Reading Mode

### ISSUE THREAD

**Issue by Rikiub** [tcmmichaelb139/obsidian-tokyonight#5]
## Differences

**The icon:**

![External Link Indicator](https://github.com/tcmmichaelb139/obsidian-tokyonight/assets/114118274/7ebcc6dd-a77e-4725-bf53-2d60d93ed060)

### Reading Mode

> ![Default Theme (Reading Mode)](https://github.com/tcmmichaelb139/obsidian-tokyonight/assets/114118274/d717c817-53b8-45b0-9c10-d138d3db1d04)
> Default

> ![Tokyo Night (Reading Mode)](https://github.com/tcmmichaelb139/obsidian-tokyonight/assets/114118274/d3bc1758-0a44-44ed-a033-682338792b8a)
> ***Tokyo Night***

### Live Preview

> ![Default Theme (Live Preview)](https://github.com/tcmmichaelb139/obsidian-tokyonight/assets/114118274/da6c464c-999a-497c-9e12-583bd09e56ca)
> Default

> ![Tokyo Night (Live Preview)](https://github.com/tcmmichaelb139/obsidian-tokyonight/assets/114118274/846406ef-2d6a-4338-872f-93213f4ead81)
> Tokyo Night

**Comment by tcmmichaelb139** [comment]
Fixed
