### ISSUE TITLE
Is it possible to add various checkbox support?

### ISSUE THREAD

**Issue by quarkquartet** [tcmmichaelb139/obsidian-tokyonight#6]
Many themes support various checkboxes for tasks.

e.g. Border theme.
<img width="42" alt="image" src="https://github.com/tcmmichaelb139/obsidian-tokyonight/assets/26316540/8b5036b9-f7db-4940-a6f8-f4ab2bd5e8fe">

That will make Tokyo Night a perfect theme.

**Comment by tcmmichaelb139** [comment]
It should be added with the latest commit.
